### PR TITLE
fixes #28-added the templates for the issue creation and pull request…

### LINKED ISSUE #28: Create a template for Issues and Pull Requests

### PR DESCRIPTION
**Pull request by sarnava1**
… creation

### CODE REVIEW

**Comment by sarnava1** [comment]
@sumedhe please review this PR.

**Comment by sarnava1** [comment]
@sumedhe I created the templates for the issue creation and for opening pull requests as they should be but I am getting minor errors from codacy. Can you please review this and give your feedback so that they can be merged?

**Comment by sumedhe** [comment]
You can check Codacy review results for this PR from [here](https://app.codacy.com/app/sumedhe/senz/pullRequest?prid=3362819)

**Comment by sarnava1** [comment]
@sumedhe I had checked the errors from there and I think the errors they pointed out are trivial and are required to be there. They said that we should not use '_' in the file naming but for creating templates for issue creation and pull requests we require to keep '_' in the file naming system. I think we can ahead with this PR and merge it.

**Comment by sarnava1** [comment]
@sumedhe have you thought as to what to do to this PR?

**Comment by YashMeh** [comment]
@sarnava1 there are 25+ issues with the PR
Try doing these..
- Do camel casing of the filename
- Remove colon from headings 
- Properly indent the contents

**Pull request merged**
