### PR TITLE
fixed password view and show confirm password

### LINKED ISSUE #148: hide/show password follow inverted logic, no visibility for confirm password
**Describe the bug**

1.  Hide/Show password button on login/signup pages follow inverted logic as compared to normal, for eg. Google

2.  Same hide/show button should work for both password and confirm password

**To Reproduce**
1. Go to /login and /signup
2. Click on the visibility icon
3.1 The logic is inverted
3.2 There is no icon to see the password entered for confirmed password box

**Expected behavior**

1. The logic should be inverted for better UX

2. Same icon should be used for both password and confirm password at /signup

**Screenshots**

_**a) Toggle Logic**_
_Senz signup screen:_
image

_Google signup screen:_
senz1 1

_**b)For confirm Password:**_
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 80.0.3987.87 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by m1-key**
Fixes #148 
Few changes from the PR #135 . In that show password was only applied to password section , now it has been applied to confirm password also and now the eye-icon will be open when password is hidden and crossed when password is not hidden. 
Show confirm password feature has been implemented.

Screenshots of the same has been attached : 
Earlier it was like this : 

Now it looks like this : 

Show Password : 

Show confirm Password :

### CODE REVIEW

**Comment by m1-key** [comment]
@YashMeh  sir can you please review this ?

**Comment by AdityaSrivast** [comment]
@m1-key an issue is already open for this functionality at #148 asking for mentor's review

**Comment by m1-key** [comment]
@AdityaSrivast sir then should I mention that issue in this PR ?

**Comment by AdityaSrivast** [comment]
@m1-key its alright now. You can fix it. :+1:  I was actually waiting for the mentors' approval to fix the same. 
Ideally, you should mention on the issue that you want to work on it, before proceeding, and if no-one else is working on it. Take care from next time onwards :+1:

**Comment by m1-key** [comment]
> @m1-key its alright now. You can fix it. 👍 I was actually waiting for the mentors' approval to fix the same.
> Ideally, you should mention on the issue that you want to work on it, before proceeding, and if no-one else is working on it. Take care from next time onwards 👍

Ok sir I will take care from next time , for sure.

**Pull request merged**
